CREATE DATABASE IF NOT EXISTS tienda_online;

USE tienda_online;

CREATE TABLE IF NOT EXISTS Usuario (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(255) NOT NULL,
  contrasenia VARCHAR(255) NOT NULL,
  telefono VARCHAR(20) NOT NULL,
  correo VARCHAR(255) NOT NULL UNIQUE,
  direccion VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CategoriaProducto (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Producto (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  descripcion TEXT,
  precio DECIMAL(10, 2) NOT NULL,
  cantidad INT UNSIGNED NOT NULL,
  talla VARCHAR(20),
  color VARCHAR(20),
  imagen VARCHAR(255),
  categoria_id INT UNSIGNED,
  FOREIGN KEY (categoria_id) REFERENCES CategoriaProducto (id)
);

CREATE TABLE IF NOT EXISTS Cart (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT UNSIGNED NOT NULL,
  producto_id INT UNSIGNED NOT NULL,
  cantidad INT UNSIGNED NOT NULL,
  FOREIGN KEY (usuario_id) REFERENCES Usuario (id),
  FOREIGN KEY (producto_id) REFERENCES Producto (id)
);

CREATE TABLE IF NOT EXISTS Contacto (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  telefono VARCHAR(20) NOT NULL,
  correo VARCHAR(255) ,
  mensaje TEXT NOT NULL,
  leido VARCHAR(2) DEFAULT 'No'
);
